### ISSUE TITLE
Better support for polygons with holes and multipolygons

### ISSUE THREAD

**Issue by rowanwins** [w8r/martinez#16]
Gday @w8r 

I'm just thinking through how we can better support polygons with holes and multipolygons to get the ball rolling on this issue...

Currently the input is simply the coordinates array which is obviously limited. One option would be to go up a level in the geojson heirachy to the `geometry` object which includes the type such as `Polygon` or `MultiPolygon`. That would more clearly align the input to the geojson spec which probably is a pro (although possibly a con for those unfamiliar with geojson). Alternatively we could come up with a suitable object to use an input format
   - I don't think it'a great idea for us to try and 'guess' whether the user is trying to input a multipoly or poly with a hole so I'd prefer a more structured input approach

Is this a reasonable starting point for this, to start by addressing the format of the input polys?

cc @DenisCarriere

**Comment by w8r** [comment]
I think reading geojson properties would be a step back in terms of what algorithm does, but providing a flag or an api to make a distinction between those types should be highly useful.

I am thinking of 2 ways:
* force input of "multipolygons with holes", always: `[[contour, hole, hole], [contour, hole]]`
* introduce an api to build different types of inputs, like `.addContour(), addHole()`

**Comment by rowanwins** [comment]
Thanks for clarifying @w8r . Im happy with your first suggestion, I'll take a first stab at implementing that and will keep you posted.

**Comment by w8r** [comment]
thank you!

**Comment by DenisCarriere** [comment]
@w8r 👍 A valid MultiPolygon input is exactly what you described

> force input of "multipolygons with holes", always: [[contour, hole, hole], [contour, hole]]

And a valid Polygon input would be `[contour, hole, hole]`.

However, I don't think it's the input the issue, the concern is the output which is always formatted as a list of LineStrings.

## Current output:

- Simple Polygon: `[contour]`
- Polygon with holes: `[contour, hole, hole]`
- Split into two polygons: `[contour, contour]`
- Split into two polygons with holes: `[contour, hole, contour, hole, hole]`

## Expected output:

- Simple Polygon: `[contour]`
- Polygon with holes: `[contour, hole, hole]`
- `**change`: Split into two polygons: **`[[contour], [contour]]`**
- `**change`: Split into two polygons with holes: **`[[contour, hole], [contour, hole, hole]]`**

I don't think including `.addContour(), addHole()` would be beneficial, as long as the user inputs a valid [Polygon](http://geojson.org/geojson-spec.html#id4)/[MultiPolygon](http://geojson.org/geojson-spec.html#id7) geometry based on the GeoJSON spec. It's a lot better to focus your energy on the algorithm instead of the user input/output formats (let the GeoJSON spec handle that).

You can always include some basic input validation ([TurfJS Polygon](https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.js#L77-L96)) to see if the (Multi)Polygon has valid coordinates.

**Comment by DenisCarriere** [comment]
> @rowanwins although possibly a con for those unfamiliar with geojson

I doubt there's any other formats that are more popular than GeoJSON, even [WKT](https://en.wikipedia.org/wiki/Well-known_text) (used in QGIS & PostGIS is following the same similar syntax.
![image](https://cloud.githubusercontent.com/assets/550895/25101352/fb153018-2381-11e7-91da-9e09f5f6bb2d.png)


![image](https://cloud.githubusercontent.com/assets/550895/25101345/f3c08d26-2381-11e7-9d17-2bb79cbd8f81.png)

**Comment by rowanwins** [comment]
Gday @DenisCarriere 

Yep agreed that it's the output that needs improving, I just wanted to make sure we were starting from a common understanding of the input structure as I think that will flow through and inform the output structure.

Anyway made a bit of a start last night and will try to keep working it through over the next few evenings.

Cheers

**Comment by DenisCarriere** [comment]
👍 Awesome! You are correct, both input & output has to be standardized in some way.

Looking forward to see the new changes!

**Comment by w8r** [comment]
The weak spot for output is when it tries guessing as in original paper, whether it was a hole or a contour, all of that is in the `connectEdges` procedure, especially the point where it decides about marking contour as a hole from odd-even rule, and then actually just reverts the points clockwise instead of putting it to the end of contours array. 
Do you have any test data to play with?

**Comment by rowanwins** [comment]
Thanks for the advice @w8r , I should be fine for test data.

**Comment by DenisCarriere** [comment]
@w8r As for test data, we've got a few GeoJSON in the [newest PR](https://github.com/Turfjs/turf/pull/644) `@turf/difference` [`/test/in`](https://github.com/Turfjs/turf/tree/261295aae74905b9491c9bdddb12c504c567645b/packages/turf-difference/test/in) & [`/test/out`](https://github.com/Turfjs/turf/tree/261295aae74905b9491c9bdddb12c504c567645b/packages/turf-difference/test/out).

How the test data works is they are all FeatureCollections:
- 1st Feature is the `source`
- 2nd Feature is the `target`

The benefits of having them in GeoJSON is you can visually see the the geometry directly in GitHub or GeoJSON.io, for use in `martinez` you can simply extract the [`coordinates`](https://github.com/Turfjs/turf/blob/261295aae74905b9491c9bdddb12c504c567645b/packages/turf-difference/test/in/multi-polygon-target.geojson?short_path=aa97dd2#L9-L54) for the input.

**Comment by w8r** [comment]
thanks, I'll use them

**Comment by rowanwins** [comment]
can I request the label `brain-melt` get added to this task?!

Progress has been minimal so far. 

- I wondered whether it was worth adding an additional boolean property on each `SweepEvent` designating whether the point was originally part of an exterior or interior ring, I was simply going to call it something like `isExteriorRing` and default to true. I was hoping this might help downstream in the `connectEdges` procedure. Adding this property is fairly simple through the `processPolygon` procedure.

- The complexity of the `connectEdges` procedure is taking a fair bit of headspace to try and understand what is going on. 

Anyway I'll press on and try and step through it slowly

**Comment by w8r** [comment]
that's my biggest problem as well - as soon as one month had passed after I finished, it became incredibly difficult to remember how it worked.
Actually, what I did was just giving contours numbers, which already can tell you a lot about whether it is an exterior or interior ring. But then connectEdges is a mess, I really have to sit down and sink it in again

**Comment by rowanwins** [comment]
Well miracle above miracles I've managed to get something vaguely functioning! I'll send through a pull request to show the rough approach.

I need to run it against a few more test cases (actually a lot more test cases but it's getting late!) and it needs a major sanity check. I still have my doubts that it's going to work for everything but there is one way to find out.

**Comment by w8r** [comment]
@rowanwins WOW, send it to me, I'll check it
great job

**Comment by rowanwins** [comment]
Let's not get too excited just yet, I could be delirious because I've stared at array loops for too long!

**Comment by w8r** [comment]
I know the feeling

**Comment by DenisCarriere** [comment]
@w8r has this fix been published yet?

**Comment by w8r** [comment]
no, but look at this!
<img width="686" alt="screenshot 2017-05-28 21 38 28" src="https://cloud.githubusercontent.com/assets/26884/26531689/4befea14-43ee-11e7-9d81-5c80c463a61d.png">

I might have just fixed the degeneracy, that was chasing this lib for many months!

I am thinking about making a new release today, after I'll check some other edge cases. I think it would make sense to release right away and putting the performance optimisations, that I planned, into the next release

**Comment by w8r** [comment]
@rowanwins @DenisCarriere changes are released in `0.2.0`

Next major release will be focused on performance optimization and precision fixes

**Comment by DenisCarriere** [comment]
👍 Awesome stuff!

**Comment by rowanwins** [comment]
Yay :)
